VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "enuBit"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
'TOP DOWN

Option Compare Binary
Public Property Get IO1() As Variant
    IO1 = 1
End Property
Public Property Get IO2() As Variant
    IO2 = 2
End Property
Public Property Get IO3() As Variant
    IO3 = 4
End Property
Public Property Get IO4() As Variant
    IO4 = 8
End Property
Public Property Get IO5() As Variant
    IO5 = 16
End Property
Public Property Get IO6() As Variant
    IO6 = 32
End Property
Public Property Get IO7() As Variant
    IO7 = 64
End Property
Public Property Get IO8() As Variant
    IO8 = 128
End Property

Public Property Get IO01() As Variant
    IO01 = 1
End Property
Public Property Get IO02() As Variant
    IO02 = 2
End Property
Public Property Get IO03() As Variant
    IO03 = 4
End Property
Public Property Get IO04() As Variant
    IO04 = 8
End Property
Public Property Get IO05() As Variant
    IO05 = 16
End Property
Public Property Get IO06() As Variant
    IO06 = 32
End Property
Public Property Get IO07() As Variant
    IO07 = 64
End Property
Public Property Get IO08() As Variant
    IO08 = 128
End Property

Public Property Get IO09() As Variant
    IO09 = 256
End Property
Public Property Get IO10() As Variant
    IO10 = 512
End Property
Public Property Get IO11() As Variant
    IO11 = 1024
End Property
Public Property Get IO12() As Variant
    IO12 = 2048
End Property
Public Property Get IO13() As Variant
    IO13 = 4096
End Property
Public Property Get IO14() As Variant
    IO14 = 8192
End Property
Public Property Get IO15() As Variant
    IO15 = 16384
End Property
Public Property Get IO16() As Variant
    IO16 = 32768
End Property

Public Property Get IO17() As Variant
    IO17 = 65536
End Property
Public Property Get IO18() As Variant
    IO18 = 131072
End Property
Public Property Get IO19() As Variant
    IO19 = 262144
End Property
Public Property Get IO20() As Variant
    IO20 = 524288
End Property
Public Property Get IO21() As Variant
    IO21 = 1048576
End Property
Public Property Get IO22() As Variant
    IO22 = 2097152
End Property
Public Property Get IO23() As Variant
    IO23 = 4194304
End Property
Public Property Get IO24() As Variant
    IO24 = 8388608
End Property










Attribute 