var menuBase = new menuObject(5,5,20,false,'Media/202.gif',false,true,"Media/PlusMinus/Black/plus.gif","Media/PlusMinus/Black/minus.gif",true,"Media/TreeLines/Black/top.gif","Media/TreeLines/Black/mid.gif","Media/TreeLines/Black/btm.gif","Media/TreeLines/Black/hline.gif","Media/TreeLines/Black/vline.gif");
menuBase.menuItems[0] = new menuItemObject("Media/Bullet Icons/overview.gif","","","","Blacklawn","Serif","2","Black","Introduction.htm","help","",false);
menuBase.menuItems[1] = new menuItemObject("Media/Bullet Icons/topic.gif","","","","The Story","Serif","2","Black","thestory.htm","help","",false);
menuBase.menuItems[2] = new menuItemObject("Media/Bullet Icons/topic.gif","","","","Controls","Serif","2","Black","controls.htm","help","",false);
menuBase.menuItems[3] = new menuItemObject("Media/Bullet Icons/topic.gif","","","","Playing","Serif","2","Black","howtoplay.htm","help","",false);
menuBase.menuItems[4] = new menuItemObject("Media/Bullet Icons/topic.gif","","","","Console","Serif","2","Black","Console.htm","help","",false);
menuBase.menuItems[5] = new menuItemObject("Media/Bullet Icons/topic.gif","","","","Multiplayer","Serif","2","Black","Multiplayer.htm","help","",false);
menuBase.menuItems[6] = new menuItemObject("Media/Bullet Icons/topic.gif","","","","Data Model","Serif","2","Black","datafiles.htm","help","",false);
menuBase.menuItems[7] = new menuItemObject("Media/Bullet Icons/world.gif","","","","Neotext.org","Serif","2","Black","http://www.neotext.org","_new","",false);
