VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CallBacks"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
'TOP DOWN

Public Function ProcedureDefined1()

End Function

Public Function ProcedureDefined2()

End Function
'
''Public xParam1 As Long
''Public xParam2 As Boolean
''Public xParam3 As Boolean
''Public xParam4 As Boolean
'
'
''Public Event ControlService(lEvent As Long)
''Public Event StartService(Success As Boolean)
''Public Event PauseService(Success As Boolean)
''Public Event ContinueService(Success As Boolean)
''Public Event StopService()
''Public Event LoggedOffService()
'
'Public Property Get UserDefined1() As Long
'
'End Property
'Public Property Let UserDefined1(ByRef RHS As Long)
'    RHS = UserDefined1
'End Property
'
'Public Property Get UserDefined2() As Boolean
'
'End Property
'Public Property Let UserDefined2(ByRef RHS As Boolean)
'    RHS = UserDefined2
'End Property
'
'Public Property Get UserDefined3() As Boolean
'
'End Property
'Public Property Let UserDefined3(ByRef RHS As Boolean)
'    RHS = UserDefined3
'End Property
'
'Public Property Get UserDefined4() As Boolean
'
'End Property
'Public Property Let UserDefined4(ByRef RHS As Boolean)
'    RHS = UserDefined4
'End Property
'
'Public Sub ProcedureDefined1()
'
'End Sub
'
'Public Sub ProcedureDefined2()
'
'End Sub
'
''Public Sub ControlService(lEvent As Long)
''    Success = True
''End Sub
''Public Sub StartService(Success As Boolean)
''    Success = True
''End Sub
''Public Sub PauseService(Success As Boolean)
''    Success = True
''End Sub
''Public Sub ContinueService(Success As Boolean)
''    Success = True
''End Sub
''Public Sub StopService()
''
''End Sub
''Public Sub LoggedOffService()
''
''End Sub
''
''
