VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IMenuDefined"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public FileNewEnabled As Boolean

Public FileOpenEnabled As Boolean

Public ImportImageEnabled As Boolean

Public ImportPatternEnabled As Boolean

Public ImportMaterialEnabled As Boolean

Public FileSaveEnabled As Boolean

Public FileSaveAsEnabled As Boolean

Public EditCutEnabled As Boolean

Public EditCopyEnabled As Boolean

Public EditPasteEnabled As Boolean

Public EditSelectAllEnabled As Boolean


Public Sub FileNew()

End Sub

Public Sub FileOpen()

End Sub

Public Sub ImportImage()

End Sub

Public Sub ImportPattern()

End Sub

Public Sub ImportMaterial()

End Sub

Public Sub FileSave()

End Sub

Public Sub FileSaveAs()

End Sub

Public Sub EditCut()

End Sub

Public Sub EditCopy()

End Sub

Public Sub EditPaste()

End Sub

Public Sub EditSelectAll()

End Sub


